language: node_js

node_js:
  - '12'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: sitmun

cache:
  directories:
    - ./node_modules

before_install:
  - npm set //npm.pkg.github.com/:_authToken $GITHUB_API_KEY

install:
  - npm ci

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless --code-coverage
  - npm run sonar

before_deploy:
  - ng build --configuration=testdeployment --baseHref="https://sitmun.github.io/admin-app/"

deploy:
  skip_cleanup: true
  provider: script
  script: ./build-scripts/deploy.sh
  on:
    all_branches: true
